package com.matafe.application2;
/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App1WebClient {
    public boolean someLibraryMethod() {
        return true;
    }
}
